[phases.setup]
nixPkgs = ["...", "php83Extensions.intl", "php83Extensions.zip"]
aptPkgs = ["libicu-dev", "libzip-dev"]

[phases.install]
cmds = [
    "composer install --no-dev --optimize-autoloader --no-scripts --no-interaction",
    "npm ci"
]

[phases.build]
cmds = [
    "npm run build",
    "php artisan storage:link",
    "php artisan optimize"
]

[start]
cmd = "php artisan migrate --force && php artisan serve --host=0.0.0.0 --port=${PORT:-8080}"
